BuildScripts/chocolateyinstall.ps1
BuildScripts/setup.ps1

To disable desktop icon creation install like this: choco install boxstarter -packageParameters "/nodesktopicon"

#26 Added Option for disabling Boxstarter desktop icon

---

Web/Learn/SimplePackage.cshtml

Hi. Just happened to notice. Great tool!

command changes

---

Boxstarter.WinConfig/Set-ExplorerOptions.ps1
BuildPackages/example-light/tools/chocolateyInstall.ps1
BuildPackages/example/tools/chocolateyInstall.ps1
Web/CreatingPackages.cshtml
Web/WebLauncher.cshtml

(GH-166) Corrected typo in parameter name

---

Boxstarter.WinConfig/Set-WindowsExplorerOptions.ps1

Add 'Expand To Open Folder'

---

Web/WinConfig.cshtml

(GH-169) Added docs for ExpandToOpenFolder switch

---

Boxstarter.Bootstrapper/Get-PendingReboot.ps1
Boxstarter.Bootstrapper/Test-PendingReboot.ps1

The resolution for the issue #126

The function Get-PendingReboot updated to version from 27/07/2015

---

Boxstarter.Chocolatey/Boxstarter.Chocolatey.psm1
Boxstarter.Chocolatey/Chocolatey.ps1
Boxstarter.Chocolatey/Invoke-BoxstarterFromTask.ps1

That squash was soo quick and easy! Thanks again for all the help!

Added Invoke-BoxstarterFromTask

---

Web/WebLauncher.cshtml

Hello,
In the interest of speeding up (my) learning curve, I added an example of specifying packages in the URL without reboots.

Added no reboot example when launching from URL

---

Web/InstallingPackages.cshtml

This is why text editors should come with "previously used words" autocomplete, and why I love using Vim with NeoComplete or YouCompleteMe when I can. :)

Code example and typo fixes

---

Boxstarter.WinConfig/Set-TaskbarOptions.ps1
Web/WinConfig.cshtml

I created a new pull request so the file I added and deleted wouldn't be included

Allow set notification area settings

---

Boxstarter.WinConfig/Set-ExplorerOptions.ps1

The two options seem to be backwards; noticed this today when configuring my shiny new laptop :)

Fix behavior of Set-ExplorerOptions

---

BuildScripts/default.ps1

https://github.com/chocolatey/choco/blob/master/CHANGELOG.md

Bump vendored choco to 0.10.6

---

Boxstarter.WinConfig/Install-WindowsUpdate.ps1

My powershell isn't pretty and it's kinda hard to test this change since it's a bit of a race condition, but I think this should fix issue #267.
I'm open to suggestions on doing this a better way.

Handle the case where the Windows Update Agent is updating itself. 

---

Boxstarter.WinConfig/Set-WindowsExplorerOptions.ps1
Web/WinConfig.cshtml

Adds a "Show Ribbon" option for the Set-WindowsExplorerOptions.
Related to the "Minimize the Ribbon" option in Windows Explorer.

Add Show Ribbon in Windows Explorer

---

Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1

This will address [#229](https://github.com/mwrock/boxstarter/issues/229)

Added support for expanding Boxstarter modules on Server Core

---

.gitignore
Boxstarter.ClickOnce/Boxstarter.WebLaunch.csproj
Boxstarter.sln
BuildScripts/build.ps1
BuildScripts/default.ps1
BuildScripts/nuget/Boxstarter.Azure.nuspec
BuildScripts/nuget/Boxstarter.Bootstrapper.nuspec
BuildScripts/nuget/Boxstarter.Chocolatey.nuspec
BuildScripts/nuget/Boxstarter.Common.nuspec
BuildScripts/nuget/Boxstarter.HyperV.nuspec
BuildScripts/nuget/Boxstarter.TestRunner.nuspec
BuildScripts/nuget/Boxstarter.WinConfig.nuspec
BuildScripts/nuget/Boxstarter.nuspec
Web/Web.csproj
Web/packages.config

@mwrock @ferventcoder can I get you both to have a look at these changes, and to let me know what you think?

Added Signing with Chocolatey Code Signing Certificate

---

Boxstarter.Bootstrapper/en-US/about_boxstarter_bootstrapper.help.txt
BuildScripts/bootstrapper.ps1

Fix typo for "properly" (minor edit)

---

deployment.md

Added the Visual Studio requirements needed to work with the project.

(#321) Added VS requirements

---

BuildScripts/build.ps1

Replaced the deprecated WindowsAzurePowerShell package in teh build script with AzurePowerShell package.

(GH-323) Replace deprecated WindowsAzurePowerShell package

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/aAskQuestion.md
.github/ISSUE_TEMPLATE/dReportPackageIssue.md
.github/ISSUE_TEMPLATE/fReportIssue.md
.github/ISSUE_TEMPLATE/kFeatureRequest.md
.github/ISSUE_TEMPLATE/vSecurityDisclosure.md
.github/PULL_REQUEST_TEMPLATE.md
COMMITTERS.md
CONTRIBUTING.md
README.md

* Added GitHub issue and pr templates
* Added docs on contributing, committing and updated the readme with details of these

(GH-333) Update instructions

---

COMMITTERS.md
CONTRIBUTING.md
README.md

* Fix formatting
* Fix invalid urls
* Fix urls pointing to choco documentation

(GH-333) Fix docs

---

BoxStarter.Common/Enter-DotNet4.ps1
BoxStarter.Common/Invoke-FromTask.ps1
BoxStarter.Common/Out-BoxstarterLog.ps1
BoxStarter.Common/Write-BoxstarterLogo.ps1
Boxstarter.Azure/Restore-AzureVMCheckpoint.ps1
Boxstarter.Bootstrapper/Invoke-Boxstarter.ps1
Boxstarter.Bootstrapper/Start-UpdateServices.ps1
Boxstarter.Bootstrapper/Stop-UpdateServices.ps1
Boxstarter.Chocolatey/Chocolatey.ps1
Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1
Boxstarter.Chocolatey/Invoke-ChocolateyBoxstarter.ps1
Boxstarter.HyperV/Enable-BoxstarterVM.ps1
Boxstarter.TestRunner/Publish-BoxstarterPackage.ps1
Boxstarter.WinConfig/Update-ExecutionPolicy.ps1
BuildPackages/ad-hoc-tests/tools/chocolateyInstall.ps1
BuildPackages/exception-package/tools/chocolateyInstall.ps1
BuildPackages/force-reboot/tools/chocolateyInstall.ps1
BuildPackages/test-package2/tools/chocolateyInstall.ps1
BuildScripts/chocolateyinstall.ps1
BuildScripts/default.ps1
IntegrationTests/test-helper.ps1
tests/Chocolatey/Chocolatey.tests.ps1
tests/Common/Invoke-FromTask.tests.ps1

fixed spelling of "write-XY" commands to "Write-XY"

---

BuildScripts/nuget/Boxstarter.Azure.nuspec
BuildScripts/nuget/Boxstarter.Bootstrapper.nuspec
BuildScripts/nuget/Boxstarter.Chocolatey.nuspec
BuildScripts/nuget/Boxstarter.Common.nuspec
BuildScripts/nuget/Boxstarter.HyperV.nuspec
BuildScripts/nuget/Boxstarter.TestRunner.nuspec
BuildScripts/nuget/Boxstarter.WinConfig.nuspec

Add the package parameters to the Chocolatey .nuspec files that were missed from PR #54

(GH-26) Add package parameters to Chocolatey .nuspec description

---

CONTRIBUTING.md

* Updated the style and coding standards
* Fixed markdown issues
* Updated TOC
* Tidied up

Add style coding guidelines

---

Web/InstallBoxstarter.cshtml

Document the uninstall process for Boxstarter.
Closes #378

(GH-378) Add uninstall process

---

.github/ISSUE_TEMPLATE/fReportIssue.md

* Fix broken comments at the top of the template
* Clarify the instructions

Fix issue template and clarify instructions

---

Boxstarter.WinConfig/Boxstarter.WinConfig.psm1
Boxstarter.WinConfig/Boxstarter.WinConfig.pssproj
Boxstarter.WinConfig/Set-BoxstarterTaskbarOptions.ps1
Boxstarter.WinConfig/Set-TaskbarOptions.ps1
Boxstarter.WinConfig/Set-TaskbarSmall.ps1
Web/WinConfig.cshtml

Adds support for setting the options for multiple displays in Windows 10.

(GH-399) Multi-monitor support in Set-TaskbarOptions

---

Web/BoxstarterResources.cshtml

Adds a Community resources section with blog posts, articles and tools.
Fixes #428

(GH-428) Add Community resources section

---

Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1
Web/InstallingPackages.cshtml

Add documentation for the `DelegateChocoSources` switch of the `Install-BoxstarterPackage` command.
Fixes #435

(GH-435) Docs for DelegateChocoSources

---

Web/InstallBoxstarter.cshtml

The issue can be seen at the bottom of https://boxstarter.org/InstallBoxstarter

Fix chocolatey links

---

Web/InstallBoxstarter.cshtml

As requested in https://github.com/chocolatey/boxstarter/pull/462#issuecomment-762650222

Update chocolatey uninstall url

---

README.md

Fix Markdown lint warnings and add Appveyor build badge
Fixes #483

(GH-483) Tidy markdown and add Appveyor badge

---

README.md

Fixed typo in README.md
Old link goes to 404 Not Found page
Tested with new link
N/A

(doc) Fixed typo in README.md

---

BuildScripts/default.ps1

This PR fixes an issue with building branches or PRs with long names, by copying the methods already in use by [Chocolatey Cake Recipe](https://github.com/chocolatey/Chocolatey.Cake.Recipe/blob/develop/Chocolatey.Cake.Recipe/Content/gitversion.cake#L134-L147).
Previously, builds with long prereleases (e.g. where the branch name was spectacularly lengthy) were failing to be packed by Chocolatey due to a known issue with long versions.
- Tested the build with the new logic and a long branch name (as I understand it, the branch I'm submitting from should fail, previously)
* [~] Feature / Enhancement (non-breaking change)
* [~] Breaking change (fix or feature that could cause existing functionality to change)
* [~] PowerShell code changes.
Fixes #524 
* [~] Requires a change to the …

(#524) Fix Build Handling of Long Prerelease

---

Boxstarter.Chocolatey/New-PackageFromScript.ps1

Boxstarter Launch from Web only works on second run
