chocolatey/boxstarter

Boxstarter.WinConfig/Boxstarter.WinConfig.psm1
Boxstarter.WinConfig/Set-DesktopOptions.ps1

Offering the addition for setting desktop options for hiding/showing desktop icons and hiding/showing icon titles.
On new machines, in addition to showing hidden files and file extensions, I often hide desktop icons and turn on the Desktop toolbar on the taskbar.  I researched turning on the Desktop toolbar but didn't find an acceptable solution.
Thanks for consideration.
Ed

Adding Set-DesktopOptions for show/hide icons and titles

---

Boxstarter.Chocolatey/Chocolatey.ps1

This will prevent chocolatey from writing an error to the console when installing something.

Telling chocolatey that it's ok to install files by passing -y.

---

BuildScripts/bootstrapper.ps1

I get error 400 bad request when visiting via http, it looks they've made the site https now.

Chocolatey now uses httpS

---

Web/WebLauncher.cshtml

As per #116 - Minor documentation typo fix and added instruction on how to execute a single text file using the WebLauncher

#116 - Added docs on how to execute a single text file using the WebLauncher

---

Boxstarter.WinConfig/Set-TaskbarOptions.ps1

Added a new parameter to the TaskbarOptions function called `Combine` which has three possible values:`Always`, `Full`, and `Never`. These values correspond to the drop down values in the highlighted panel.

Add Taskbar option for setting icon combination style.

---

Boxstarter.Chocolatey/Chocolatey.ps1

I ran into this Int64 error message when trying to install visual studio 2015 (a local package, not one on chocolatey.org). I'm not exactly sure if the error is actually associated with the install, but it seemed like the fix was to add a secondary check in ConvertTo-PSString to look for [int64] types.

Added [int64] check to ConvertTo-PSString

---

Boxstarter.WinConfig/Boxstarter.WinConfig.psm1
Boxstarter.WinConfig/Boxstarter.WinConfig.pssproj
Boxstarter.WinConfig/Disable-GameBarTips.ps1
Web/WinConfig.cshtml

This function allows to disable the annoying tips from the XBox GameBar
in Windows 10 that are shown when a game starts up. There are two
problems with this:
1. Apparently, it breaks some games
2. Windows 10 also shows it for some applications like the x64 version
of Total Commander

Add Disable-GameBarTips

---

Boxstarter.WinConfig/Set-WindowsExplorerOptions.ps1
Web/WinConfig.cshtml

This change adds 3 Windows 10 specific options. You can now tweak settings for:
- Open File Explorer To Quick Access or Computer
- Show recently used files
- Show frequently used folders/directories
All this taken from [Issue 99](https://github.com/mwrock/boxstarter/issues/99)
Tabs converted to spaces simply for consistency, not religiosity. Sorry that it looks to be such a large set of changes to almost all lines. It's only a whitespace change, and I sure didn't mean to step into tabs/spaces. I used PowerShell ISE to dev this change, and it uses spaces by default and this is the result...
I followed existing naming conventions, and simply created lines of code where they belonged alongside similar reg key modifiers.
The naming convention was like `Enable\Disable<something>QuickAccess` as …

Windows 10 WindowsExplorerOptions  for Quick Access

---

Boxstarter.WinConfig/Boxstarter.WinConfig.psm1
Boxstarter.WinConfig/Boxstarter.WinConfig.pssproj
Boxstarter.WinConfig/Disable-BingSearch.ps1
Web/WinConfig.cshtml

Disables the Bing Internet Search when searching from the search field
in the Taskbar or Start Menu.

Disable-BingSearch

---

Boxstarter.Bootstrapper/Test-PendingReboot.ps1
tests/Bootstrapper/Test-PendingReboot.tests.ps1
tests/Tests.pssproj

Moved the check on the result inside the scriptblock because the parent scope variable was not updated inside the Invoke-Command.
Included a test to prove the result

Fix for Test-PendingReboot not returning result of Get-PendingReboot.

---

BuildScripts/nuget/Boxstarter.Common.nuspec

Boxstarter.Common 2.9.5 was [marked as rejected](https://chocolatey.org/packages/BoxStarter.Common/2.9.5) on Chocolatey. This breaks the Boxstarter bootstrapper, as Boxstarter.Common >= 2.9.5 is a dependency of the Boxstarter package.
This commit adds the [required](https://github.com/chocolatey/package-validator/wiki/TagsNotEmpty) _tags_ element to the nuspec.

Add required tags element to BoxStarter.Common nuspec

---

Web/Learn/SimplePackage.cshtml

It was incorrectly pointing at `Learn/InstallBoxstarter`, which does not exist.

Fix InstallBoxstarter dead link

---

Boxstarter.Chocolatey/Chocolatey.ps1

Fixes issue #283 by adding the missing file64 parameter to the Install-ChocolateyInstallPackage override as referenced by https://github.com/mwrock/boxstarter/issues/283#issuecomment-352024589.  Otherwise, packages that were attempting to use this newer parameter for 64-bit installs were always installed as 32-bit when using Boxstarter.

GH-283 Add file64 param to InstallPackageOverride

---

Boxstarter.sln
BuildScripts/VERIFICATION.txt
BuildScripts/default.ps1
BuildScripts/nuget/Boxstarter.Azure.nuspec
BuildScripts/nuget/Boxstarter.Bootstrapper.nuspec
BuildScripts/nuget/Boxstarter.Chocolatey.nuspec
BuildScripts/nuget/Boxstarter.Common.nuspec
BuildScripts/nuget/Boxstarter.HyperV.nuspec
BuildScripts/nuget/Boxstarter.TestRunner.nuspec
BuildScripts/nuget/Boxstarter.WinConfig.nuspec

* Adds the VERIFICATION.txt file to the build artifacts
* Adds the VERIFICATION.txt file to the packages

(GH-312) Add package verification for Chocolatey checks

---

BuildScripts/default.ps1

Excludes copying the files below to the build directory so they are not packaged:
* log4net.xml
* chocolatey.xml
* *.pssproj files from the Boxstarter modules

(GH-311) Stop copying XML and PSSPROJ files

---

BuildScripts/default.ps1

fixes #324 by ensuring that the package step always pulls the choco dll and its deps before building the remoting zip and also before packing the nugets.
If you run `build package` before this PR in a clean space with no boxstarter.zip, the generated zip will not have the chocolatey.dll AND the nuget will not include the boxstarter.zip. With this PR, the `boxstarter.chocolatey.nupkg` should include the `boxstarter.zip` which should include the `chocolatey.dll` and log4net.
This only worked before because of a particular workflow I had with testing that does not necessarily make sense now.
Signed-off-by: mwrock <matt@mattwrock.com>

(GH-324) ensure chocolatey.dll and its deps are packaged in the remoting zip during package task

---

Boxstarter.ClickOnce/Boxstarter.WebLaunch.csproj
BuildScripts/build.ps1
BuildScripts/default.ps1

Resolves #227 - allows CI build to pass by disabling ClickOnce signing if no certificate is present
Also tidy up appveyor build by suppressing Chocolatey progress output.

(GH-227) Fix build

---

BuildScripts/chocolateyUninstall.ps1
BuildScripts/default.ps1
BuildScripts/nuget/Boxstarter.Chocolatey.nuspec
BuildScripts/setup.ps1

Remove the start menu shortcut that is created by the Boxstarter.Chocolatey package.

(GH-336) Fix uninstall leftover shortcut

---

Boxstarter.WinConfig/Set-WindowsExplorerOptions.ps1

enable/disable the snap-assist feature in windows 10 - as suggested in #308
This adds two switches to the function `Set-WindowsExplorerOptions`
* `EnableSnapAssist`
* `DisableSnapAssist`

(GH-308) Enable/disable SnapAssist Windows Setting

---

Web/packages.config

bumped bootstrap (web toolkit) from version 3.0.2 to 3.4.1
for notes on what changed see https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/
I've tested the website (Project "Web" in Boxstarter.sln) locally with IIS Express - everyting seems to be working as expected.

bumped bootstrap 3.0.2 to 3.4.1

---

Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1
Web/InstallingPackages.cshtml

This updates the documentation for "Using BoxstarterConnectionConfig objects" to align with the code. The original example code did not work.
Fixes #331

(GH-331) BoxstarterConnectionConfig Params

---

Web/CreatingPackages.cshtml
Web/InstallBoxstarter.cshtml
Web/InstallingPackages.cshtml
Web/Learn/RemotePackageWithArtifacts.cshtml
Web/Learn/SimplePackage.cshtml
Web/Learn/WebLauncher.cshtml
Web/Learn/_ContentLayout.cshtml
Web/TestingPackages.cshtml
Web/UsingBoxstarter.cshtml
Web/VMIntegration.cshtml
Web/WebLauncher.cshtml
Web/_ContentLayout.cshtml
Web/_Sitelayout.cshtml
Web/index.cshtml

This PR resolves issues #120, #183, #390 and also allows images to be responsive on mobile devices to prevent annoying horizontal scrollbars.
- When the viewport is <767px, the left side navigation will now collapse and be accessible through a button. 
- The Bootstrap columns were fixed as a result of this, and now the links are clickable on any viewport.
- The classes "pull-left" and "pull-right" have been replaced with the appropriate classes as stated in the Bootstrap 3.4.1 documentation. 
- Extra "col-" classes have been removed as they are not allowed within "media" objects and could cause the layout to break
- The class "img-responsive" has been added to most images, which makes them scalable on any viewport and removes any unnecessary horizontal scrollbars.

(GH-120)(GH-390) Resolve boxstarter.org navigation and depreciated Bootstrap classes

---

CONTRIBUTING.md

Update the PowerShell naming convention based on the discussion in #343 
Closes #343

(GH-343) Add PowerShell function naming convention

---

.editorconfig
Boxstarter.sln
CONTRIBUTING.md

Added basic .editorconfig file with the following settings:
for all
* end of line: CRLF
* insert final newline
* trim trailingi whitespace
for *.ps1 / *.psm1 / *.psd1
* charset: utf-8
* ident: spaces
* ident width: 4
also included a quick note in CONTRIBUTING.md how to install the required plugins in vscode.

(GH-347) Add .editorconfig to define project standards

---

Boxstarter.Chocolatey/Chocolatey.ps1

This should "re-enable" the possibility to pass `-RebootCodes` to Chocolatey commands in Boxstarter packages.
I stumbled across the parameter in the tests (i.e. [here](https://github.com/chocolatey/boxstarter/blob/9596ea327d597419e80e9535e01aa2923ac60619/tests/Chocolatey/Chocolatey.tests.ps1#L96)) and wanted to use this feature in my generic Boxstarter bootstrapper files, however there are several small bugs/inconsistencies that basically render this unusable in the current state.
inside a Boxstarter package:
```
cinst far 
cinst foobar -RebootCodes @(8, 3010, 42)
cinst barz
```
when installing `samplePackage.ps1` via Boxstarter wrapper (`BoxStarter.bat`), `Invoke-Reboot` will be triggered immediately after a package (far, foobar or barz) returned a "valid reboot code".

(GH-389) fix RebootCodes option for cinst wrapper

---

Boxstarter.WinConfig/Install-WindowsUpdate.ps1

At least on 1709 and 1803 pro/enterprise right after clean installation on this simple test https://raw.githubusercontent.com/tetatetit/mybox/master/test.ps1 (the key nuance is "Notify for download and auto install" AUOptions in Windows Update policy which can be set via gpedit.msc "Computer Configuration\Administrative Templates\Windows Components\Windows Update\Configure Automatic Updates"): Result - last update is ever impossible to install via Install-WindowsUpdate but infinite reboot loop instead

(GH-344) isDownloaded lies sometimes

---

Boxstarter.WinConfig/Boxstarter.WinConfig.psm1
Boxstarter.WinConfig/Set-BoxstarterPageFile.ps1
Boxstarter.WinConfig/Set-PageFile.ps1

This is only a new function: Set-PageFile that enable BoxStarter to set the swapfile on the box where is getting executed.
Set-PageFile is an advanced function which can be used to adjust virtual memory page file size.
.PARAMETER  <InitialSize>
Setting the paging file's initial size.
.PARAMETER  <MaximumSize>
Setting the paging file's maximum size.
.PARAMETER  <DriveLetter>
Specifies the drive letter you want to configure.
.PARAMETER  <SystemManagedSize>
Allow Windows to manage page files on this computer.
.PARAMETER  <None>        
Disable page files setting.
.PARAMETER  <Reboot>      
Reboot the computer so that configuration changes take effect.
.PARAMETER  <AutoConfigure>
Automatically configure the initial size and maximumsize.
.EXAMPLE
C:\PS> Set-PageFile -InitialSize 1024 …

(GH-387) Set page file

---

BuildScripts/bootstrapper.ps1

If Boxstarter fails to download Chocolatey then it doesn't catch that failure and continues on with the rest of the bootstrapper script which will just start throwing misleading exceptions. Catch the failure and just end the script.
Closes #376

(GH-376) Add bootstrapper exception catch

---

BuildScripts/bootstrapper.ps1

Enables TLS 1.2 support in `bootstrapper.ps1` which downloads Boxstarter from chocolatey.org.
Tested locally and this works.
Fixes #420

(GH-420) Enable TLS 1.2

---

Boxstarter.Chocolatey/Chocolatey.ps1

(GH-265) Disable reboot check for anything but install, uninstall & upgrade

---

Web/WinConfig.cshtml

Removes the `-Lock` and -`Unlock` parameters from the Set-TaskBarOptions function example as they cannot be used with the `-AlwaysShowIconsOn` or `-AlwaysShowIconsOff` parameters.
Fixes #424

(GH-424) Fix Set-TaskBarOptions function doc

---

Web/InstallBoxstarter.cshtml

Update the web install instructions to allow for TLS 1.2 to be set and Execution Policy to be turned off for that install session.
This is not needed at the moment but will be in future so makes sense to include it now.

(GH-419) Update web install instructions to allow for TLS 1.2 

---

Boxstarter.WinConfig/Disable-BingSearch.ps1
tests/WinConfig/Disable-BingSearch.tests.ps1

In Windows release 2004 the registry key to disable bing search in the taskbar and start menu has changed.
Fixes #434
It disables Bing Search across all Windows platforms.
This was tested on a Windows 10 2004 system. It was also tested with the Pester tests that are included as part of the commit.

(GH-434) Fix disabling bing search for Win release 2004+

---

Boxstarter.Chocolatey/Chocolatey.ps1
tests/Chocolatey/Chocolatey.tests.ps1

(GH-444) Refactor code around Boxstarter specific parameters to make it clearer

---

CONTRIBUTING.md

In the current CONTRIBUTING documentation, the method documented for adding the remote assumes that the user is using ssh agent forwarding.  However, most users are going to be using HTTPS cloning when they add the remote to the forked repo.  I modified the CONTRIBUTING documentation to include the appropriate command to run when adding the remote using HTTPS cloning.
Without this change, users who want to contribute to the project will not be able to follow the instructions outlined in the documentation, as an Access Denied error will occur when running git fetch if the remote is added using SSH agent forwarding.
I modified the Contributing.md document so that it included the command to add the remote using https cloning, as most users looking to contribute to the project will be using …

(GH-446) Updates documentation with important info

---

Boxstarter.Chocolatey/Chocolatey.ps1
tests/Chocolatey/Chocolatey.tests.ps1

In the code that evaluates Boxstarter Package Parameters, 'StopOnPackagaFailure' is only recognized (and therefore stripped from the 'chocolatey parameter string) if, and only if 'RebootCodes' were present in the original parameter string.
Fixes #451

(GH-451) Fix Boxstarter Package Parameter '-StopOnPackageFailure'

---

Boxstarter.WinConfig/Set-WindowsExplorerOptions.ps1
Web/WinConfig.cshtml

Even though Boxstarter has existing functionality to modify Windows
Explorer's settings, the existing functionality did not allow for user's
to configure the "Use check boxes to select items" setting.  This commit
adds that functionality to the existing set-windowsexploreroptions
function.
Boxstarter will continue to work even if this change is not implemented, as this change is meant as an enhancement, not a bug fix.
I modified the Set-WindowsExplorerOptions.ps1 file in the following ways:
- Added two additional parameters that follow the same naming convention of all of the other parameters: "EnableItemCheckBoxes" and "DisableItemCheckBoxes"
- Added comment based help entries for each parameter describing their functionality
- Added two lines of code which would configure the check box …

(GH-443) Adds Windows Explorer item check box view

---

.teamcity/pom.xml
.teamcity/settings.kts

This PR add TeamCity build configuration for this project which can be imported into a TeamCity server using the [Versioned Settings](https://www.jetbrains.com/help/teamcity/storing-project-settings-in-version-control.html) feature.
Fixes #488 
Storing TeamCity build configuration next to the code it is building and in soruce control itself for change tracking, etc.
This has been tested against an available test TeamCity server.
Build steps were observed to have been imported, and the build could be run and suceeded.
Enhancement: Doesn't touch the project code itself, isn't a breaking change, doesn't _technically_ fix a bug.

(GH-488) Add TeamCity build config

---

Boxstarter.WinConfig/Set-BoxstarterTaskbarOptions.ps1
Web/WinConfig.cshtml

Added the ability to enable / disable the search box on the Windows 10 taskbar.
Fixes #491 
Allows further customisation of the Windows taskbar.
This has been run in the Boxstarter shell on a clean Windows 10 sandbox.

(#491) Add disable / enable taskbar search box

---

.teamcity/settings.kts
Boxstarter.ClickOnce/Boxstarter.WebLaunch.csproj
BuildScripts/default.ps1

The main change in this PR is enabling the signing of the ClickOnce and PowerShell files using a certificate stored in the local certificate store rather than a PFX file on disk.
In completing these changes, I noted that the ClickOnce signing didn't include a timestamp, so I have added this.
For completeness of TeamCity builds, I have also specified that the web directory should be collected as a compressed archive artifact.
Fixes #493
Signing certificates aren't always available as PFX files, and supporting the certificate store allows for that use case. This change adds a second signing method so as to not break existing builds that are using a PFX file.
These changes have been synced through to a development TeamCity server with a test signing cert in the certificate store. The build …

(GH-493)(CU-ENGTASKS-505) Enable signing from local certificate store

---

BuildScripts/default.ps1
BuildScripts/nuget/Boxstarter.Azure.nuspec
BuildScripts/nuget/Boxstarter.Bootstrapper.nuspec
BuildScripts/nuget/Boxstarter.Chocolatey.nuspec
BuildScripts/nuget/Boxstarter.Common.nuspec
BuildScripts/nuget/Boxstarter.HyperV.nuspec
BuildScripts/nuget/Boxstarter.TestRunner.nuspec
BuildScripts/nuget/Boxstarter.WinConfig.nuspec
BuildScripts/nuget/Boxstarter.nuspec

Add missing metadata to nuspec files so there are less validation warnings when packages are submitted to Chocolatey public repo.
Resolves #448
Nicer Chocolatey packages

(GH-448) Add extra metadata to nuspec files

---

Boxstarter.Bootstrapper/en-US/about_boxstarter_bootstrapper.help.txt

Fixed a typo in about_boxstarter_bootstrapper.help.txt.
Changed `bust` to `must`.
More readable documentation.
N/A
N/A (It's a trivial change)

(doc) Fixed typo in about_boxstarter_bootstrapper

---

BuildScripts/nuget/Boxstarter.Azure.nuspec
BuildScripts/nuget/Boxstarter.Bootstrapper.nuspec
BuildScripts/nuget/Boxstarter.Chocolatey.nuspec
BuildScripts/nuget/Boxstarter.HyperV.nuspec
BuildScripts/nuget/Boxstarter.TestRunner.nuspec
BuildScripts/nuget/Boxstarter.WinConfig.nuspec
BuildScripts/nuget/Boxstarter.nuspec

Updated the package iconUrl to be from one that Chocolatey owns.
Icon was pointing to somewhere we had no control over.
N/A.
Fixes #508

(#508) Fix package iconUrl to be one that Chocolatey owns

---

Boxstarter.Chocolatey/Chocolatey.ps1
Boxstarter.Chocolatey/invoke-chocolatey.ps1
tests/Chocolatey/Chocolatey.tests.ps1

Updated how `VerbosePreference` was being used to propagate the verbose setting for new `choco.exe` processes and during Boxstarter environment variable restoration.
The `VerbosePreference` parameter was not being set correctly for new `choco.exe` processes as well as when exporting Boxstarter environment variables resulting in verbose output during subprocess Chocolatey package installations.
Tested on Windows 11 (21H2 22000.593). Added a new test to check the `-Verbose` parameter is not being set incorrectly. Did not add a test to check for correct environment variable restoration since the test `Export-BoxstarterVars` in `Chocolatey.tests.ps1` failed complete -- likely a scheduled task issue.
Fixes #501

(GH-501) Fix Propagation of VerbosePreference to Reduce Verbose Logging

---

Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1

Noted in the `Install-BoxstarterPackage` function help that auto login does not work when run from 32-bit PowerShell on 64-bit operating system.
[Another PR](https://github.com/chocolatey/boxstarter.org/pull/64) was raised to update the website.
#1 indicates that this does not work so we needed to document it.
This was only a change to the PowerShell help.
N/A
N/A

(doc) Document No auto login from 32-bit PS on 64-bit OS

---

Boxstarter.TestRunner/Bootstrap.ps1
BuildScripts/bootstrapper.ps1

This commit removes the manal creation of the Chocolatey CLI directory
where the application will be installed to.
This is done as a change in the Chocolatey CLI script have changed so
that if the directory exists, Chocolatey CLI will fail to install.
This manual creation may have been needed some time in the past, but has
not been needed for several years now.
We should not create anything that is not needed to be created, and rely
on the installation script instead to know what to set up for its own
installation.
1. Copy the bootstrapper script into a new empty virtual environment without Chocolatey CLI installed.
2. Run `Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; . …

(#548) Remove creation of Chocolatey Install Directory
